version: '3'
services:

  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: mysql
    expose:
      - 3306
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  web:
    container_name: web
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      DATABASE_NAME: football
      DATABASE_USER: 'admin'
      DATABASE_PASSWORD: j20020607
      DATABASE_PORT: 3306
      DATABASE_HOST: database-1.c2vt7g52k0os.ap-northeast-2.rds.amazonaws.com
      DJANGO_SETTINGS_MODULE: madcamp_week4_BE.settings
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  app:
  dbdata:
