# Generated by Django 3.2.16 on 2024-01-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadium',
            name='teamId',
            field=models.IntegerField(default=47, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stadium',
            name='stadium_image',
            field=models.ImageField(blank=True, null=True, upload_to='stadium_images/'),
        ),
    ]
